services:
  - type: web
    name: abu-alaa-crm
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER
        value: true
      - key: DJANGO_SETTINGS_MODULE
        value: abu_alaa_project.settings
