# Generated by Django 5.2.3 on 2025-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='currency',
            field=models.CharField(choices=[('IQD', 'دينار عراقي'), ('USD', 'دولار أمريكي')], default='IQD', max_length=3, verbose_name='العملة'),
        ),
    ]
