# Generated by Django 5.2.3 on 2025-07-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_companysettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='page_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الصفحة الورقية'),
        ),
    ]
